// import codes from'./countryCodes.json'
// import curCodes from './currencyCodes.json'
//flags used with, country codes there too (they're not entirely ISO based)
// https://github.com/lipis/flag-icon-css

// currency codes
// https://github.com/annexare/Countries/blob/master/data/countries.json
//EUR->EU not parsed, so is USD

function mapCurrenciesToFlags() {
    var map = {}
    for (var nameCode in codes) {
        // const name = codes[nameCode]
        const country = curCodes[nameCode]
        if (country) {
            map[country.currency] = nameCode
        }
    }
    console.log(map)
}
// mapCurrenciesToFlags()

const curToFlag = {
    "EUR": "EU",
    "AED": "AE",
    "AFN": "AF",
    "XCD": "VC",
    "ALL": "AL",
    "AMD": "AM",
    "AOA": "AO",
    "": "AQ",
    "ARS": "AR",
    "USD": "US",
    "AUD": "TV",
    "AWG": "AW",
    "AZN": "AZ",
    "BAM": "BA",
    "BBD": "BB",
    "BDT": "BD",
    "XOF": "TG",
    "BGN": "BG",
    "BHD": "BH",
    "BIF": "BI",
    "BMD": "BM",
    "BND": "BN",
    "BOB,BOV": "BO",
    "BRL": "BR",
    "BSD": "BS",
    "BTN,INR": "BT",
    "NOK": "SJ",
    "BWP": "BW",
    "BYR": "BY",
    "BZD": "BZ",
    "CAD": "CA",
    "CDF": "CD",
    "XAF": "TD",
    "CHE,CHF,CHW": "CH",
    "NZD": "TK",
    "CLF,CLP": "CL",
    "CNY": "CN",
    "COP": "CO",
    "CRC": "CR",
    "CUC,CUP": "CU",
    "CVE": "CV",
    "ANG": "SX",
    "CZK": "CZ",
    "DJF": "DJ",
    "DKK": "GL",
    "DOP": "DO",
    "DZD": "DZ",
    "EGP": "EG",
    "MAD,DZD,MRU": "EH",
    "ERN": "ER",
    "ETB": "ET",
    "FJD": "FJ",
    "FKP": "FK",
    "GBP": "JE",
    "GEL": "GE",
    "GHS": "GH",
    "GIP": "GI",
    "GMD": "GM",
    "GNF": "GN",
    "GTQ": "GT",
    "GYD": "GY",
    "HKD": "HK",
    "HNL": "HN",
    "HRK": "HR",
    "HTG,USD": "HT",
    "HUF": "HU",
    "IDR": "ID",
    "ILS": "PS",
    "INR": "IN",
    "IQD": "IQ",
    "IRR": "IR",
    "ISK": "IS",
    "JMD": "JM",
    "JOD": "JO",
    "JPY": "JP",
    "KES": "KE",
    "KGS": "KG",
    "KHR": "KH",
    "KMF": "KM",
    "KPW": "KP",
    "KRW": "KR",
    "KWD": "KW",
    "KYD": "KY",
    "KZT": "KZ",
    "LAK": "LA",
    "LBP": "LB",
    "CHF": "LI",
    "LKR": "LK",
    "LRD": "LR",
    "LSL,ZAR": "LS",
    "LYD": "LY",
    "MAD": "MA",
    "MDL": "MD",
    "MGA": "MG",
    "MKD": "MK",
    "MMK": "MM",
    "MNT": "MN",
    "MOP": "MO",
    "MRU": "MR",
    "MUR": "MU",
    "MVR": "MV",
    "MWK": "MW",
    "MXN": "MX",
    "MYR": "MY",
    "MZN": "MZ",
    "NAD,ZAR": "NA",
    "XPF": "WF",
    "NGN": "NG",
    "NIO": "NI",
    "NPR": "NP",
    "OMR": "OM",
    "PAB,USD": "PA",
    "PEN": "PE",
    "PGK": "PG",
    "PHP": "PH",
    "PKR": "PK",
    "PLN": "PL",
    "PYG": "PY",
    "QAR": "QA",
    "RON": "RO",
    "RSD": "RS",
    "RUB": "RU",
    "RWF": "RW",
    "SAR": "SA",
    "SBD": "SB",
    "SCR": "SC",
    "SDG": "SD",
    "SEK": "SE",
    "SGD": "SG",
    "SHP": "SH",
    "SLL": "SL",
    "SOS": "SO",
    "SRD": "SR",
    "SSP": "SS",
    "STN": "ST",
    "SVC,USD": "SV",
    "SYP": "SY",
    "SZL": "SZ",
    "THB": "TH",
    "TJS": "TJ",
    "TMT": "TM",
    "TND": "TN",
    "TOP": "TO",
    "TRY": "TR",
    "TTD": "TT",
    "TWD": "TW",
    "TZS": "TZ",
    "UAH": "UA",
    "UGX": "UG",
    "USD,USN,USS": "US",
    "UYI,UYU": "UY",
    "UZS": "UZ",
    "VES": "VE",
    "VND": "VN",
    "VUV": "VU",
    "WST": "WS",
    "YER": "YE",
    "ZAR": "ZA",
    "ZMK": "ZM",
    "USD,ZAR,BWP,GBP,AUD,CNY,INR,JPY": "ZW"
}
Object.assign(curToFlag, {
    EUR: 'EU',
    USD: 'US',
    AUD: 'AU',
    GBP: "GB",
})

export default curToFlag